# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epingpong.proto\x12\x0c\x62y.mitr.grpc\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2P\n\x0fPingPongService\x12=\n\x04ping\x12\x19.by.mitr.grpc.PingRequest\x1a\x1a.by.mitr.grpc.PongResponseB\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pingpong_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _PINGREQUEST._serialized_start=32
  _PINGREQUEST._serialized_end=62
  _PONGRESPONSE._serialized_start=64
  _PONGRESPONSE._serialized_end=95
  _PINGPONGSERVICE._serialized_start=97
  _PINGPONGSERVICE._serialized_end=177
# @@protoc_insertion_point(module_scope)
